import Head from 'next/head'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'
import LargeCard from '../components/LargeCard'
import MediumCard from '../components/MediumCard'
import SmallCard from '../components/SmallCard'
export default function Home({exploreData,cardsData}) {
  return (
    <div >
      <Head>
        <title>Airbnb-clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Header/>
<Banner/>
<main className='max-w-7xl mx-auto px-8 sm:p-16 h-full'>
  <section className='pt-3 '>
    <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>
    <div className='grid sm:grid-cols-2 ld:grid-cols-3 xl:grid-cols-4'>
{exploreData.map((item)=>(
<SmallCard img={item.img} distance={item.distance} location={item.location} key={item.img} />
))}
</div>
  </section>
  <section>
    <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>
   <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3'>
    {
      cardsData.map((item)=>(
<MediumCard  key={item.img} img={item.img} title={item.title} />

    ))
    }
    </div>
  </section>
  <LargeCard img="https://links.papareact.com/4cj"
  title="The Greatest Outdoors "
  description="Wishlists curated by airbnb"
  buttonText="Get Inspired"/>
</main>
<footer>
  <Footer />
</footer>
    </div>
  )
}
export async function getStaticProps(){

  const exploreData= await fetch('https://links.papareact.com/pyp').then(res=>res.json());
  
  const cardsData= await fetch('https://links.papareact.com/zp1').then(res=>res.json());
  return{
    props:{
      exploreData,
    cardsData
    }
  }
}